services:
  db:
    image: postgres:13
    container_name: fastapi_db
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
